@startuml

(*) --> "检验输入"
If "输入的是yes " then
--> [Yes] "打印出你输入的是 yes,
执行yes操作。"
--> "结果"

else
--> "第三分支"
--> [二] "else 结果"
--> "结果"


else

 --> [No] "打印输出 No，执行no操作"
 --> [二] "else 结果"
 --> "结果"

 -->(*)



 (*) --> [输入错误] "error displaly"
--> "error deal 2"
 -->(*)
@enduml